# Generated by Django 3.0.3 on 2020-03-02 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='note',
        ),
        migrations.AlterField(
            model_name='project',
            name='pattern',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pattern'),
        ),
        migrations.AlterField(
            model_name='project',
            name='yarn',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Yarn'),
        ),
    ]
