# Generated by Django 3.0.3 on 2020-03-02 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200302_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='note',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Note'),
        ),
    ]
