# Generated by Django 3.0.3 on 2020-03-03 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200302_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='needle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Needle'),
        ),
    ]
